id: P000424
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN4982
  title: བྱང་ཆུབ་ལམ།
  author: ''
  volumes:
    e96149d000504fbc85dc46d2378383f3:
      image_group_id: I3CN4984
      title: Volume 1 of byang chub lam/
      volume_number: 1
      total_pages: 183
      base_file: v001.txt
